services:

  backend:
    build: ../backend
    container_name: backend_container
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    depends_on:
      - spark

  frontend:
    build: ../frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  spark:
    image: apache/spark:3.5.0
    container_name: spark_container
    ports:
      - "8080:8080"

  rstudio:
    image: rocker/rstudio:latest
    container_name: r_container
    ports:
      - "8787:8787"